# Generated by Django 2.0.1 on 2018-08-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
    ]
