# Generated by Django 2.0.1 on 2018-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180822_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
